CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    user_name TEXT NOT NULL UNIQUE,
    email TEXT not null unique,
    password TEXT NOT NULL
);


CREATE TABLE movie_table (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    genre TEXT NOT NULL,
    rating SMALLINT DEFAULT 0,
    watched BOOLEAN DEFAULT FALSE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

